packages:
  - apps/*
  - packages/*
  - configs/*

catalog:
  '@eslint/js': ^9.38.0
  '@hookform/resolvers': ^5.2.2
  '@tailwindcss/postcss': ^4.1.16
  '@tanstack/react-table': 8.21.3
  '@tanstack/react-query': ^5.90.6
  '@tanstack/react-query-devtools': 5.90.2
  '@trpc/client': ^11.7.1
  '@trpc/next': ^11.7.1
  '@trpc/react-query': ^11.7.1
  '@trpc/server': ^11.7.1
  '@trpc/tanstack-react-query': ^11.7.1
  '@types/node': ^22.19.0
  autoprefixer: ^10.4.21
  bcryptjs: ^3.0.2
  better-auth: 1.4.0-beta.15
  class-variance-authority: 0.7.1
  clsx: ^2.1.1
  eslint: ^9.39.0
  inquirer: ^9.3.8
  lucide-react: 0.552.0
  postcss: ^8.5.6
  prettier: ^3.6.2
  react-hook-form: ^7.66.0
  sonner: ^2.0.7
  superjson: ^2.2.5
  tailwindcss: ^4.1.16
  tailwind-merge: ^3.3.1
  tw-animate-css: ^1.4.0
  tsx: ^4.20.6
  typescript: ^5.9.3
  zod: 4.1.12
  zustand: ^5.0.8

catalogs:
  react19:
    '@types/react': ^19.2.2
    '@types/react-dom': ^19.2.2
    react: ^19.1.1
    react-dom: ^19.1.1

linkWorkspacePackages: true

publicHoistPattern:
  - '@ianvs/prettier-plugin-sort-imports'
  - prettier-plugin-tailwindcss
